[features]
seeds = false
skip-lint = false

[programs.localnet]
soar = "SoarmxsvnGcQzLGaiue8mVTko7uuEfTY5zwdKKCnQDU"
tens = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
soar = "SoarmxsvnGcQzLGaiue8mVTko7uuEfTY5zwdKKCnQDU"
tens = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet]
soar = "SoarmxsvnGcQzLGaiue8mVTko7uuEfTY5zwdKKCnQDU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/tests/*"

[workspace]
types = "client/sdk/src/idl"
members = [
    "programs/soar"
]

[test]
startup_wait = 60000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "client/tests/fixtures/mpl_token_metadata.so"
