[features]
seeds = false
skip-lint = false

[programs.localnet]
soar = "SoarNNzwQHMwcfdkdLc6kvbkoMSxcHy89gTHrjhJYkk"
tens = "Tensgwm3DY3UJ8nhF7xnD2Wo65VcnLTXjjoyEvs6Zyk"

[programs.devnet]
soar = "SoarNNzwQHMwcfdkdLc6kvbkoMSxcHy89gTHrjhJYkk"
tens = "Tensgwm3DY3UJ8nhF7xnD2Wo65VcnLTXjjoyEvs6Zyk"

[programs.mainnet]
soar = "SoarNNzwQHMwcfdkdLc6kvbkoMSxcHy89gTHrjhJYkk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Documents/Solana/Utils/safe.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/tests/*"

[workspace]
types = "client/sdk/src/idl"
members = [
    "programs/soar",
    "examples/tens"
]

[test]
startup_wait = 60000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "client/tests/fixtures/mpl_token_metadata.so"
